**出错了怎么办？**

在编写程序的过程中，我们不能够保证永远不会出错，既然程序总会有问题，我们就要用适当的方法去解决问题，比如`int('BMW')`他就或报错,这就是异常了。

现在让我们回到我们之前创建的第一个小游戏

```py
temp = input('不如来猜一下我现在心里想的数字呗')
guess = int(temp)
if guess == 6:
    pirnt('猜中了又如何，买得起宝马吗？')
else:
    print('猜错了，我想的是6')
print('游戏结束了，不玩了')
```
这个脚本呢，当用户输入的是正确的就不会有任何问题了，但只要用户输入的是一个非数字，那么这个代码就狗带了。你看
```py
不如来猜一下我现在心里想的数字呗 d
Traceback (most recent call last):
 File "D:/my_script/pyscript/work33.py", line 3, in <module>
 guess = int(temp)
ValueError: invalid literal for int() with base 10: 'd'
```
这里呢当我们输入的为字母d时，Python就跑出了一个ValueError的错误。

这里列举一下Python常见的异常

1、AssertionError，断言(assert)失败
```py
a = [1,2,3]
#assert断言，当assert后面的内容为False时报错
assert len(a) <0
```
看报错结果
```py
Traceback (most recent call last):
 File "D:/my_script/pyscript/work33.py", line 2, in <module>
 assert len(a) <0
AssertionError
```
